### ISSUE TITLE
Bugs and Feature Requests

### ISSUE THREAD

**Issue by Vykri** [FeverDevJohnny/orbomodkit#2]
Been having a great time modding Orbo. Just have a list of a few bugs and feature requests I've come across while using the mod kit. I've added numbers next to each of them to denote priority. I recognize that the mod kit isn't something you want to be maintaining and is more a gift to people that purchased the game, so I don't expect anything I've listed to be fixed. Let me know if you need any more information about any of my points below.

Bugs:
1\. JComposers with Loop enabled crash the game instead of looping
2\. "Go Orbo" stays on the screen after completing a trial when you have multiple trials in the same scene
5\. OnTrialSucceed only fires the first time
8\. Best trial time UI doesn't work when there are multiple trials in the same scene. Low priority due to perceived complexity.

Feature Requests:
3\. Camera tracking component. Similar to the Track to Player Head component, but tracks the camera instead. Useful for billboard sprites.
4\. Checkbox on Track to Player Head component to also mirror the transform's rotation. Useful for carrying objects on Orbo's head like in the base game.
9\. Anti-Guttering. Similar to the anti-guttering used for the Impact Controller. Orbo can currently get stuck in bad geometry. Low priority due to how this could potentially have game breaking implications if done improperly.

Documentation:
7\. Trial override BGM must be inactive on start

**Comment by FeverDevJohnny** [comment]
Hey, thanks for emailing!

1). I'll work to get that JComposer bug fixed soon! I think I might know
what's causing it, so hopefully this can be resolved quickly.
2). You're not meant to have multiple time trials to a scene since the game
was designed for a single time trial per-level. Probably need to update the
docs to make this limitation more explicit.
3). I'll get the issue with OnTrialSucceeded fixed quickly, I probably made
a mistake programming it and had it fire when a new record is made, not
whenever a trial is completed.
4). Same issue as #2.

5). I'll get right on it! I had a feeling I was missing something. I'll
update the TrackToPlayerHead script to add an additional setting for the
player camera.
6). Sure thing! That makes perfect sense, so expect it before long.
7). Anti-Guttering will probably be a bit much right now since I'm busy
with other projects, but maybe sometime down the line I can try to fix that.

8). I'll probably just update time trials to automatically turn off the BGM
on start, I'm surprised I never accounted for this lol.

I appreciate that you reached out about these issues!

- John

**Comment by FeverDevJohnny** [comment]
Hey, pushed an update to fix the bugs and add the new stuff, I've
tested and confirmed these changes work, but I don't know if it'll be
consistent across all use cases. I guess let me know if something's still
broken!

- John

**Comment by Vykri** [comment]
Wow, fast turnaround. Thank you so much! I'll let you know if I come across any more issues. You da bes.

**Comment by Vykri** [comment]
Tested these changes today. Here's what I found:

1. The JComposers now properly loop! This is very helpful. Thank you for fixing this.
2. OnTrialSuccess now properly triggers after each completion, not just the first. However, now that I'm using OnTrialSuccess, I noticed that using this event [hides the built-in gear for completing the trial](https://github.com/FeverDevJohnny/orbomodkit/blob/main/Assets/Resources/Scripting/ShellComponents/Shell_TimeTrialManager.cs#L20-L25). For my use case, I still want to reveal a gear on initial completion, but I also want to trigger a JTrigger whenever a trial is ended (Whether they succeed, lose, or respawn/die). The way I was doing this before was to leave OnTrialSuccess empty, set OnTrialFailure (which properly triggers during a loss and respawn/die) to my JTrigger, and spawn a boxCollider that matches the final trial ring during OnTrialBegin that also triggers my JTrigger. The only downside to this is that my JTrigger would trigger if the player touched the boxCollider during the trial without touching the other rings first. So, I can either go back to that solution or create my own gear reveal via JComposer during OnTrialSuccess (not sure if that'll work since OnTrialSuccess triggers every success now instead of just the first). But, I think the best option would be for there to be a new event added to the TrialManager called OnSuccessFirstTime (similar to the gear part's OnCollectionCutsceneEndFirstTime) that hides the default gear reveal.
3. The new Track To Player Camera component doesn't seem to work properly. It is acting the same as Track To Player Player Head component. I have a video showcasing this if you're unable to reproduce the issue.
4. The new checkbox for Track To Player Head to Align To Transform works great! Got Orbo carrying around things on his noggin no problem!

I really appreciate the fixes. Again, I recognize that you don't need to do any of this.

**Comment by FeverDevJohnny** [comment]
Hey there,
You can have JTriggers be oneshot if necessary, which will effectively do
the same thing as what you're requesting (where it'll only run events the
first time you've completed a time trial). It's just a toggle on the
script, towards the top of the component's inspector.
The reason I don't allow for JTrigger events on completing a time trial
alongside the standard gear part spawning behavior is because gear part
spawning takes control of the player's camera during the cutscene, and this
could easily conflict with JTrigger events that are also meant to
manipulate the camera in some way after finishing a time trial. The main
idea is that if you're using JTriggers, you're essentially taking the
reigns over the game's default behavior.

You mentioned wanting a JTrigger to run whenever the trial is ended,
regardless of the reason why. Here's an idea on how to do that:

You have 3 JTriggers, all of them are OnDemand.

The first JTrigger is hooked into OnTrialSuccess. This JTrigger's sole job
is to call the two other JTriggers' OnDemand functions.

The second JTrigger is concerned with the events that should run if the
trial ends for any reason. The first trigger already invokes this one's
OnDemand if we win, so we just need to slot this JTrigger into the On Trial
Failure event slot and we're good here. Now when we win or lose, this event
is always called, indicating the trial has ended in some way.

Our third and final JTrigger is the oneshot event for completing a time
trial successfully. This is called from our first JTrigger as well. Here
you can organize whatever reward is necessary for the player.

One shots are reset whenever the scene reloads, but if you need to manually
reset them for any reason there are API calls you can use to re-prime a
oneshot trigger. Check the JTrigger API reference if you need better
clarity on this behavior.

Finally, the track to player camera component thing was a very silly typo I
made while trying to get this update out, it's been corrected so I'll
publish a new update soon to correct that.

Thanks for your feedback!

- John

**Comment by Vykri** [comment]
Hmm, looks like your proposed solution would require me to create my own "gear reveal" JComposer for the one-shot OnTrialSuccess JTrigger which is what I was trying to avoid. That's fine though, I understand the resistance to having the option to run a JTrigger alongside the gear reveal.

Just tested out the Track To Player Camera component and it seems to be working now, so I'll close this issue. Thanks again for the quick response and fix for this!
